name: Android CI (dev)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  dev-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Decode google-services.json
      env:
        GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
      run: |
        echo "Decoding google-services.json..."
        echo $GOOGLE_SERVICES_JSON_BASE64 | base64 --decode > app/google-services.json
        echo "google-services.json created successfully."

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run Android Lint
      run: ./gradlew lint

    - name: Run Unit Tests
      run: ./gradlew testDebugUnitTest
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
